### ISSUE TITLE
Can't resolve ./-computed-store in ...ember-macro-helpers

### ISSUE THREAD

**Issue by ChristopherConnock** [embroider-build/embroider#285] opened 2019-07-16 22:01 UTC
Building on Windows 10 with Ember 3.11.

I am getting the following error with [ember-macro-helpers](https://github.com/kellyselden/ember-macro-helpers). I tried forcing the use of the latest build (4.2.0) to no avail. It is used in ember-moment and ember-awesome-macros.

ERROR Summary:
  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
    at factory.create (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\Compilation.js:821:10)
    at factory (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Users\511\Documents\GitHub\roast-ember\node_modules\neo-async\async.js:2830:7
    at C:\Users\511\Documents\GitHub\roast-ember\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Users\511\Documents\GitHub\roast-ember\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Users\511\Documents\GitHub\roast-ember\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\511\Documents\GitHub\roast-ember\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
  - code: [undefined]
  - codeFrame: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
  - errorMessage: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (C:\Users\511\Documents\GitHub\roast-ember\node_modules\broccoli-plugin\index.js:7:31)
    at new PackagerRunner (C:\Users\511\Documents\GitHub\roast-ember\node_modules\@embroider\core\src\to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (C:\Users\511\Documents\GitHub\roast-ember\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (C:\Users\511\Documents\GitHub\roast-ember\ember-cli-build.js:54:39)
    at Builder.readBuildFile (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:51:14)
    at Builder.setupBroccoliBuilder (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:65:22)
    at new Builder (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:31:10)
    at ServeTask.run (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\tasks\serve.js:49:7)
    at Promise.resolve.then (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\command.js:239:24)
    at tryCatcher (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:326:21)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
        at PackagerRunner (@embroider/webpack)
-~- created here: -~-
    at new Plugin (C:\Users\511\Documents\GitHub\roast-ember\node_modules\broccoli-plugin\index.js:7:31)
    at new PackagerRunner (C:\Users\511\Documents\GitHub\roast-ember\node_modules\@embroider\core\src\to-broccoli-plugin.js:10:13)
    at Object.defaultPipeline [as compatBuild] (C:\Users\511\Documents\GitHub\roast-ember\node_modules\@embroider\compat\src\default-pipeline.js:30:12)
    at module.exports (C:\Users\511\Documents\GitHub\roast-ember\ember-cli-build.js:54:39)
    at Builder.readBuildFile (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:51:14)
    at Builder.setupBroccoliBuilder (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:65:22)
    at new Builder (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\builder.js:31:10)
    at ServeTask.run (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\tasks\serve.js:49:7)
    at Promise.resolve.then (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\lib\models\command.js:239:24)
    at tryCatcher (C:\Users\511\Documents\GitHub\roast-ember\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:326:21)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/webpack
  - nodeName: PackagerRunner
  - originalErrorMessage: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
  - stack: ModuleNotFoundError: Module not found: Error: Can't resolve './-computed-store' in 'C:\Users\511\AppData\Local\Temp\embroider\8f2d44\node_modules\ember-macro-helpers'
    at factory.create (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\Compilation.js:821:10)
    at factory (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:397:22)
    at resolver (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at C:\Users\511\Documents\GitHub\roast-ember\node_modules\neo-async\async.js:2830:7
    at C:\Users\511\Documents\GitHub\roast-ember\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (C:\Users\511\Documents\GitHub\roast-ember\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (C:\Users\511\Documents\GitHub\roast-ember\node_modules\enhanced-resolve\lib\Resolver.js:184:12)
    at hook.callAsync (C:\Users\511\Documents\GitHub\roast-ember\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (C:\Users\511\Documents\GitHub\roast-ember\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)

=================================================================================

**Comment by scottkidder** [comment] 2019-07-23 12:18
I can confirm this as well on Linux on ember-cli@3.10.1

It seems to be caused by ember-macro-helpers not having a file at `./-computed-store` and instead providing `-computed-store` by doing a monkey patch [](https://github.com/kellyselden/ember-macro-helpers/blob/master/vendor/monkey-patch-ember-computed.js)

**Comment by void-mAlex** [comment] 2020-02-07 23:57
Ran into this as well running ember-cli@3.15.2 linux
Any workarounds?

**Comment by ef4** [comment] 2020-02-08 00:05
I think this is fixed on master.

**Comment by void-mAlex** [comment] 2020-02-08 13:37
thank you for the quick response
I've followed to CONTRIBUTING steps to compile and try out master and I can confirm the build now completes and assets get generated but the whole app no longer functions
I've seen these warnings for the build:
```
WARNING in ./node_modules/ember-data/adapters/errors.js 1:0-213
"export 'AdapterError' was not found in '@ember-data/adapter/error'
 @ ./assets/blog.js

WARNING in ./helpers/not-eq.js 1:0-87
"export 'notEq' was not found in '../node_modules/ember-truth-helpers/helpers/not-equal'
 @ ./assets/blog.js

WARNING in ./helpers/responsive-image-resolve.js 1:0-122
"export 'responsiveImageResolve' was not found in '../node_modules/ember-responsive-image/helpers/responsive-image-resolve'
 @ ./assets/blog.js

WARNING in ./helpers/route-is.js 1:0-81
"export 'routeIs' was not found in '../node_modules/empress-blog/helpers/route-is'
 @ ./assets/blog.js

WARNING in ./helpers/utc.js 1:0-114
"export 'utc' was not found in '../node_modules/empress-blog-casper-template/node_modules/ember-moment/helpers/utc'
 @ ./assets/blog.js
```
should I raise this as a separate issue? for some other quick info that might be relevant it's a blog app using empress prember and a default template

**Comment by ef4** [comment] 2020-02-08 14:04
This warnings are generally harmless but they’re all real bugs in the
addons they’re talking about. These addons try to reexport nonexistent
things.

It would be helpful for someone to send PRs that clean these up so people
stop seeing the warnings.

**Comment by void-mAlex** [comment] 2020-02-26 08:38
#381 fixed this for me

**Closed** 2022-04-29 07:42 UTC
