### ISSUE TITLE
Support for external modules within ember addons

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#159] opened 2019-05-04 13:48 UTC
@ef4 I put together what I believe is a representative example of the `shenanigans` addon we encountered yesteday -> https://github.com/stefanpenner/addon-shenanigans

List of known issues:

* name + moduleName() differ
* addon/index.js imports shenanigans/bar which although contained within this modules moduleName is provided via pre-built vendor tree
* treeForVendor pulls in an external file, and uses the ember-cli-babel addon to compile it's contents, including it's es module

**Note: I have also included it's other custom behavior, just in-case it that behavior also causes grief.**

---

I haven't had a chance yet to add the appropriate test cover such an add-on to embroider, but if I have a few free minutes this weekend I plan to. Just a warning, It is possible I wont have time, so I wanted to at-least provide a sketch of the known issue in-case you do have time to work on it before I can implement the test.

**Comment by stefanpenner** [comment] 2019-05-11 15:09
After further analysis, we believe: `addon/index.js imports shenanigans/bar which although contained within this modules moduleName is provided via pre-built vendor tree` is something embroider should likely not support at all.

Our approach was to simplify the add-on, and have it use ember-auto-import. This resulted in all the add-on's custom build code being removed, working with class apps, and working with embroider.

We will keep an eye on `treeForVendor` issue, if it arises in ways that aren't fix by the above mentioned approach, we will revisit.

**Comment by ef4** [comment] 2019-05-13 18:10
Yes, we're going to leave this WONTFIX for the present. We can re-assess if this problem crops up in more places.

The summary statement of the problem is: all the modules *inside* an ember addon are expected to be statically resolvable at build time. This is true for v1 addons because we compile them to v2 addons, and for v2 addons its true by construction.

We do support referring to modules that won't be found until runtime (aka "externals"), but those modules are not allowed to be namespaced inside an ember addon.

**Closed by ef4** 2019-05-13 18:10 UTC

**Comment by stefanpenner** [comment] 2019-05-16 16:29
@ef4 :+1:
