### ISSUE TITLE
@embroider/webpack building forever

### ISSUE THREAD

**Issue by c0rydoras** [embroider-build/embroider#1532] opened 2023-07-14 13:07 UTC
# Problem
I can't serve or build any embroider projects anymore (embroider versions tested 2.x, 3.x), its stuck at `⠋ building... [@embroider/webpack]`. I also tried different package managers (npm, pnpm, yarn) all resulting in the same state of `⠋ building... [@embroider/webpack]` forever. This started after a system upgrade, since then i have tried these things:
- reinstall node, npm etc. 2x
- restarted my system 3x
- deleting all caches and node_modules 2x 

# System details
OS: `archlinux`
NPM: `9.8.0`
yarn: `1.22.19`
pnpm: `8.6.7`
node: `16, 18 and 20`
ember-source: `4.12 and 5`
ember-cli: `4.12 and 5`
ember-data: `4.11, 4.12 and 5`

**Comment by NullVoxPopuli** [comment] 2023-07-14 23:13
Any chance you have a reproduction repo that demonstrates this problem?

**Comment by BobrImperator** [comment] 2023-07-15 13:26
@NullVoxPopuli I happen to have one :)
You can check out this `ember-simple-auth` branch https://github.com/mainmatter/ember-simple-auth/pull/2604
I'm currently migrating the addon to V2 and also wanted to add tests for embroider specifically, but it fails for both embroider scenarios I've created.

Running ESA is pretty straightforward:
- `clone` the repo
- `pnpm install`
- `pnpm install && pnpm run --filter test-app test:one embroider-lts-4.12`

**Comment by BobrImperator** [comment] 2023-07-15 13:49
I seem to have fixed this. Now it just throws and doesn't hang.
Turns out that `pnpm` was using an incorrect node version `20.*`, pinning to `18.16.1` fixed the hangup.

**Comment by C0rydoras** [comment] 2023-07-15 13:51
@NullVoxPopuli to reproduce the problem simply create a new ember app with `ember-cli` and the `--embroider` flag

**Comment by BobrImperator** [comment] 2023-07-15 14:00
@C0rydoras is it possible that you have installed `nodejs` and `pnpm` with a package manager like `pacman` or `yay`?
If so pnpm could end up using a wrong version of nodejs.

Please see if there's any warning in your console at the very start.

**Comment by C0rydoras** [comment] 2023-07-15 14:03
@BobrImperator yes, but the problem does not only occur when using pnpm but also when using yarn or npm

**Comment by NullVoxPopuli** [comment] 2023-07-15 14:45
> to reproduce the problem simply

I ran 
```bash
❯ npx ember-cli@latest new test-embroider --embroider --yarn
```

<details><summary>and got success</summary>

```
❯ npx ember-cli@latest new test-embroider --embroider --yarn
Need to install the following packages:
  ember-cli@5.1.0
Ok to proceed? (y) y
installing app
Ember CLI v5.1.0

✨  Creating a new Ember app in /home/nullvoxpopuli/Development/tmp/test-embroider:
  create .editorconfig
  create .ember-cli
  create .eslintignore
  create .eslintrc.js
  create .github/workflows/ci.yml
  create .prettierignore
  create .prettierrc.js
  create .stylelintignore
  create .stylelintrc.js
  create .template-lintrc.js
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create config/ember-cli-update.json
  create config/environment.js
  create config/optional-features.json
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.js
  create tests/helpers/index.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep

🚧  Installing packages... This might take a couple of minutes.
yarn: Installed dependencies

🎥  Initializing git repository.
Git: successfully initialized.

🎉  Successfully created project test-embroider.
👉   Get started by typing:

  $ cd test-embroider
  $ yarn start

Happy coding!

~/Development/tmp took 1m2s 
❯ cd test-embroider/

test-embroider on  main 

   

❯ yarn start
yarn run v1.22.19
$ ember serve

Build successful (6517ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime >= 5%)                         | Total (avg)  
--------------------------------------------------------+--------------
@embroider/webpack (1)                                  | 3898ms       
Babel: @ember/test-helpers (1)                          | 761ms     
```

</details>

My environment info:
```
❯ ember -v
ember-cli: 5.1.0
node: 18.16.0
os: linux x64

❯ which node
/home/nullvoxpopuli/.volta/bin/node

❯ which yarn
/home/nullvoxpopuli/.volta/bin/yarn

❯ yarn --version
1.22.19

❯ node --version
v18.16.0

```

**Comment by C0rydoras** [comment] 2023-07-15 14:58
@NullVoxPopuli what linux distro?

**Comment by NullVoxPopuli** [comment] 2023-07-15 15:04
```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

❯ uname -a
Linux hephaestus 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by C0rydoras** [comment] 2023-07-15 15:12
Installing the package managers & node with volta fixed the problem :D thank you

**Comment by void-mAlex** [comment] 2023-07-15 20:04
it we actually have a problem on node 20 we should keep this issue open

**Comment by NullVoxPopuli** [comment] 2023-08-15 14:44
How I reproduced in a separate embroider app:
- clone: https://github.com/universal-ember/ember-primitives/
- `pnpm i`
- `pnpm build`
- `cd docs-app`
- `volta pin node@20`
- `pnpm start`

**Comment by ef4** [comment] 2023-08-15 14:55
Confirmed that the above reproduction does not happen on Mac.

**Comment by void-mAlex** [comment] 2023-08-15 14:56
reproduced with Ubuntu 22 running in WSL on windows 10

**Comment by SolPier** [comment] 2023-08-15 15:05
reproduced with:
```
$ lsb_release -a
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
$ node --version
v20.5.1
```
(not using 'volta' but 'n' for node versions)

**Comment by mansona** [comment] 2023-08-30 14:56
@void-mAlex @NullVoxPopuli can we confirm that @jakesjews's suggestion fixes `ember-primitives` too? I'm just trying to make sure that we are confident that this is the same issue 👍

**Comment by NullVoxPopuli** [comment] 2023-08-30 15:32
Confirm, `UV_USE_IO_URING=0 pnpm start` resolves the issue for `ember-primitives` (after being configured for node 20)

**Comment by jakesjews** [comment] 2023-08-30 16:45
Node 20.3.0 updated libuv which added support for using linux io_uring in the filesystem instead of the thread pool. Setting UV_USE_IO_URING=0 disables io_uring. I'm not sure if its a bug with the io_uring stuff or if the performance improvement exposed some sort of race condition in a library somewhere

**Comment by void-mAlex** [comment] 2023-09-25 11:19
issue has now been reported on node 18.18 (and NOT happening on 18.17) -some of these are versions that GH actions run on

**Comment by void-mAlex** [comment] 2023-10-10 14:50
I've confirmed this is resolved in node 20.8.0

**Comment by mansona** [comment] 2023-10-10 14:58
It looks like Node 18.18.1 is working through release now too: https://github.com/nodejs/node/pull/50066

**Comment by void-mAlex** [comment] 2023-10-27 16:15
closing as 18.18.1 is out with a fix for the issue and is available in github ci as well

**Closed by void-mAlex** 2023-10-27 16:15 UTC
Labels: has reproduction
