### ISSUE TITLE
Should we run `addonPostProcessTree` on `extraPublicTrees`?

### ISSUE THREAD

**Issue by chancancode** [embroider-build/embroider#1581] opened 2023-08-17 20:52 UTC
In the classic build pipeline, the "extra trees" passed to `app.toTree(...)` [gets combined with the "primary trees" and go through `addonPostprocessTree`](https://github.com/ember-cli/ember-cli/blob/930d36fa9c20ee398fd9340e87653f0ac4abcc0c/lib/broccoli/ember-app.js#L1328-L1331). A common use case for this hook is to minify the JavaScript with ember-cli-terser.

I understand that Embroider manages those kind of concerns internally so it doesn't need to run ember-cli-terser on the "primary" bundles, and generally it does not run `postprocessTree` on addons at all. In most cases (like terser) that would be redundant and it would require reifying things into Broccoli trees for no reason.

However, `extraPublicTrees` is supposed to have the same semantics as passing the extra trees to `app.toTree(...)`, and that's what `maybeEmbroider` does. Currently this discrepancy means that any previously minified public trees do not get the same processing when switching to Embroider. Since those are by definition _already_ Broccoli trees and do not go through the Embroider processing, I don't see any harm in running them through `addonPostprocessTree` to preserve compatibility?

It should amount to changing [compat-app](https://github.com/embroider-build/embroider/blob/cacd923c78de61d389adc1e818c3aa5c97ebf7a6/packages/compat/src/compat-app.ts#L811C1-L811C1) to do something like this:

```js
// Not 100% sure but it seems like `this.publicTree` is also missing the post-processing?
// It appears to be a straight pass-through of the unprocessed classic public tree
publicTree = this.legacyEmberAppInstance.addonPostprocessTree('all', publicTree);
```

**Comment by void-mAlex** [comment] 2023-08-17 21:26
the addonPostprocessTree is meant for addons and the fact that ember cli uses that seems like a quick hack to me.
I do not think this is a good idea to do in embroider and I don't think it should have ever been done in ember-cli in the first place it mixes things that should not go together - addon hooks and app public trees

would maybe running the hook manually before you pass the tree to embroider solve this problem and we could document a gotcha for anyone else in this scenario?

**Comment by ef4** [comment] 2023-08-17 22:23
We never run `postprocessTree('all')` because we cannot present to it the compatible input that it's expecting to see. It expects to see the output of a classic build. We deliberately produce output that is not that.

Running it only on the extra public trees is not safe, because `addonPostprocessTree('all', mergeTrees(trees))` is not equivalent to `mergeTrees(trees.map(tree => addonPostprocessTree('all', tree)))`. If we present only a subset of the files to a given transform, the transform can crash when it fails to see the other parts of the app that it expected to exist.

So while running `addonPostprocessTree('all')` might help in some cases like yours, it's just as likely to break in other cases.

**Comment by mansona** [comment] 2023-08-30 14:52
We came across this during the issue tirage and it looks like the issue is answered (albeit with a "we can't do this" kinda answer 🙈) 

I'm going to close this because it seems pretty final. If @chancancode or @ef4 disagrees and maybe you wanted to keep this open to track alternative ways to achieve the same output then feel free to re-open 👍

**Closed by mansona** 2023-08-30 14:52 UTC

**Comment by chancancode** [comment] 2023-08-30 15:27
I agree that the original phrasing of the question is infeasible but I think it's still a pretty major discrepancy that the `extraPublicTrees` are not minified when the documentation (and `maybeEmbroider`) otherwise treats it as the same thing as `app.toTree([...])`.

At minimum, I think it deserves a callout in the documentation with instructions on how to run terser on them manually, or, better yet, I think we can just run terser (and whatever post-processing these tress normally get on a classic build) on them as the spirit is to keep things the same.

**Comment by ef4** [comment] 2023-08-30 20:08
The hazard here is broccoli-asset-rev in general: everything about it doesn't apply under embroider. I agree that is worth better documenting and highlighting somehow..

**Comment by void-mAlex** [comment] 2023-08-30 22:20
I wonder if there is a path those trees could get into the app tree via an import from app code directly
