### ISSUE TITLE
Nullish coalescing operator is breaking the build

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#436] opened 2020-04-28 16:10 UTC
We have started to use the [nullish coalescing operator](https://github.com/tc39/proposal-nullish-coalescing) in our code lately using the latest ember-cli-babel release, but it looks like Embroider is not compatible with that.

```
components/q-page-selector/component.js:30: Module parse failed: Unexpected token (30:57)
You may need an appropriate loader to handle this file type.
|     let end = Math.min(offset, totalCount);
|     let start = totalCount && offset - perPage + 1;
>     return `${start}-${end} ${this.args.paginationLabel ?? 'of'} ${totalCount}`;
|   }
| 
        at PackagerRunner (@embroider/webpack)
```

@ef4 is Embroider not using the same config as ember-cli-babel?

**Comment by kturney** [comment] 2020-05-06 20:57
looks like this is probably a duplicate of https://github.com/embroider-build/embroider/issues/405?

**Comment by void-mAlex** [comment] 2023-02-22 23:05
closing as duplicate of https://github.com/embroider-build/embroider/issues/405

**Closed by void-mAlex** 2023-02-22 23:05 UTC
