### ISSUE TITLE
Build fails with ember engines + embroider in a monorepo configuration

### ISSUE THREAD

**Issue by chriseppstein** [embroider-build/embroider#644] opened 2020-12-01 19:32 UTC
I've got an issue that is blocking me from landing embroider support to http://github.com/linkedin/eyeglass

I've reproduced the issue here (without eyeglass involved): 

Steps to reproduce issue:

1. `git clone https://github.com/chriseppstein/ember-engines-and-embroider-build-issue.git`
2. `cd ember-engines-and-embroider-build-issue`
3. `yarn install`
4. `cd packages/my-embroider-app`
5. `yarn build`
6. If Step 5 succeeds, run it again.

**Comment by thoov** [comment] 2020-12-01 23:00
@chriseppstein Thanks for the steps to reproduce!

TLDR: this is a bug introduced with my lazy engine CSS PR (https://github.com/embroider-build/embroider/pull/591/)

The error produced is: 

```
Build Error (PackagerRunner) in assets/_engine_/my-lazy-engine.js

Module not found: Error: Can't resolve '../../../my-lazy-engine/my-lazy-engine.css' in '$TMPDIR/embroider/fbe523/packages/my-embroider-app/assets/_engine_'
```

Looking at the output of stage 2 we see:

```js
import { importSync as i, macroCondition, getGlobalConfig } from '@embroider/macros';
let w = window;
let d = w.define;

if (macroCondition(!getGlobalConfig().fastboot?.isRunning)) {
  i("../../../my-lazy-engine/my-lazy-engine.css");
}

d("my-lazy-engine/config/_environment_browser_", function(){ return i("../../../my-lazy-engine/config/_environment_browser_");});
d("my-lazy-engine/config/environment", function(){ return i("../../../my-lazy-engine/config/environment");});
d("my-lazy-engine/engine", function(){ return i("../../../my-lazy-engine/engine");});
d("my-lazy-engine/package", function(){ return i("../../../my-lazy-engine/package");});
d("my-lazy-engine/templates/application", function(){ return i("../../../my-lazy-engine/templates/application");});
```

The issue is that:

```js
i("../../../my-lazy-engine/my-lazy-engine.css");
```

Was added via: 
https://github.com/embroider-build/embroider/pull/591/files#diff-23d24d20889abc4014e995cea006d0f41c5fc66151a977385522474151162448R1049 even though the engine does not contain styles.

**Comment by chriseppstein** [comment] 2020-12-02 00:59
@thoov Thanks for explaining. I actually get this same error even when the application has styles. I thought that since I got the same error, I had done enough to reproduce it. I will add the css to this reproduction to make sure the error still happens and update this thread once I'm done.

**Comment by chriseppstein** [comment] 2020-12-02 01:12
@thoov I've updated my reproduction to include a vanilla css file at `addon/styles/addon.css`.

**Comment by thoov** [comment] 2020-12-02 19:06
@chriseppstein The change in #645 still fixes your new reproduction.

After you added `addon/styles/addon.css` the package meta for your lazy engine looks like this:

```json
{
  "ember-addon": {
    "version": 2,
    "auto-upgraded": true,
    "type": "addon",
    "order-index": 101,
    "lazy-engine": true,
    "implicit-modules": [
      "./engine",
      "./routes",
      "./templates/application.hbs"
    ],
    "implicit-styles": [
      "./my-lazy-engine/__COMPILED_STYLES__/my-lazy-engine.css"
    ],
    "app-js": "_app_"
  }
}
```

Where `./my-lazy-engine/__COMPILED_STYLES__/my-lazy-engine.css` does actually resolve to a correct file. The issue was that I was always forcing a file: `./my-lazy-engine/my-lazy-engine.css` into the build which is not always correct. My change in #645 now correctly reads from `implicit-styles` to grab the file name and then only if it sees something includes it.

You can verify that #645 fixes both your original reproduction and the new one by cloning my PR, running `yarn compile && yarn link`, then inside the root of your project run: `yarn link @embroider/webpack @embroider/core @embroider/compat`

**Comment by chriseppstein** [comment] 2020-12-02 19:21
@thoov Ok, thanks for verifying that and explaining how your fix works. I'll verify this is working on my eyeglass repo this morning.

**Comment by chriseppstein** [comment] 2020-12-05 04:23
@thoov This is failing in both of my applications with the following error:

```
Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
```

<details>
<summary>Stack Trace</summary>
<pre>
=================================================================================

ENV Summary:

  TIME: Fri Dec 04 2020 20:18:36 GMT-0800 (Pacific Standard Time)
  TITLE: ember
  ARGV:
  - /Users/ceppstei/.volta/tools/image/node/12.16.2/bin/node
  - /Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/packages/my-embroider-app/node_modules/.bin/ember
  - build
  - --environment=production
  EXEC_PATH: /Users/ceppstei/.volta/tools/image/node/12.16.2/bin/node
  TMPDIR: /var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/yarn--1607141908868-0.500928372896499
  - /Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/packages/my-embroider-app/node_modules/.bin
  - /Users/ceppstei/.config/yarn/link/node_modules/.bin
  - /Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/.bin
  - /Users/ceppstei/.volta/tools/image/node/12.16.2/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/ceppstei/.volta/tools/image/node/12.16.2/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/ceppstei/.volta/tools/image/node/12.16.2/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/ceppstei/.volta/tools/image/yarn/1.22.4/bin
  - /Users/ceppstei/.volta/tools/image/node/12.16.2/bin
  - /Users/ceppstei/.volta/bin
  - /Users/ceppstei/.yarn/bin
  - /Users/ceppstei/.config/yarn/global/node_modules/.bin
  - /Users/ceppstei/.nvm/versions/node/v10.8.0/bin
  - /Users/ceppstei/.rbenv/shims
  - /Users/ceppstei/.rbenv/bin
  - /usr/local/linkedin/bin
  - /opt/subversion/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Users/ceppstei/bin
  - /Users/ceppstei/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 2141872128
  TOTALMEM: 17179869184
  UPTIME: 1923994
  LOADAVG: 1.99658203125,3.107421875,3.8876953125
  CPUS:
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz - 2500
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 36.0
  - http_parser: 2.9.3
  - icu: 65.1
  - llhttp: 2.0.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.40.0
  - node: 12.16.2
  - openssl: 1.1.1e
  - tz: 2019c
  - unicode: 12.1
  - uv: 1.34.2
  - v8: 7.8.279.23-node.34
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
    at Function.resolveSync [as sync] (/Users/ceppstei/Projects/contrib/embroider/node_modules/resolve/lib/sync.js:89:15)
    at AppBuilder.impliedAddonAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:189:55)
    at AppBuilder.impliedAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:121:27)
    at AppBuilder.implicitScriptsAsset (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:313:40)
    at AppBuilder.insertEmberApp (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:279:29)
    at AppBuilder.prepareAsset (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:461:18)
    at AppBuilder.prepareAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:471:18)
    at AppBuilder.updateAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:538:27)
    at AppBuilder.build (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:619:38)
    at WaitForTrees.buildHook (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/build-stage.js:37:31)
  - code: [undefined]
  - codeFrame: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
  - errorMessage: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/ceppstei/Projects/contrib/embroider/packages/core/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new WaitForTrees (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/Users/ceppstei/Projects/contrib/embroider/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/to-broccoli-plugin.js:10:26)
    at defaultPipeline (/Users/ceppstei/Projects/contrib/embroider/packages/compat/src/default-pipeline.js:43:12)
    at module.exports (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/packages/my-embroider-app/ember-cli-build.js:25:10)
    at Builder.readBuildFile (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:29:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/ceppstei/Projects/contrib/embroider/packages/core/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new WaitForTrees (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/wait-for-trees.js:30:9)
    at CompatApp.get tree (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/build-stage.js:26:16)
    at CompatApp.<anonymous> (/Users/ceppstei/Projects/contrib/embroider/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/to-broccoli-plugin.js:10:26)
    at defaultPipeline (/Users/ceppstei/Projects/contrib/embroider/packages/compat/src/default-pipeline.js:43:12)
    at module.exports (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/packages/my-embroider-app/ember-cli-build.js:25:10)
    at Builder.readBuildFile (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/Users/ceppstei/Projects/reproductions/ember-engines-and-embroider-build-issue/node_modules/ember-cli/lib/models/builder.js:29:10)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
  - stack: Error: Cannot find module './vendor/loader/loader.js' from '/private/var/folders/5d/nv4rw7n52d5fl3qjrw8xx6_80008nv/T/embroider/86b565/packages/my-embroider-app/node_modules/@embroider/synthesized-vendor'
    at Function.resolveSync [as sync] (/Users/ceppstei/Projects/contrib/embroider/node_modules/resolve/lib/sync.js:89:15)
    at AppBuilder.impliedAddonAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:189:55)
    at AppBuilder.impliedAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:121:27)
    at AppBuilder.implicitScriptsAsset (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:313:40)
    at AppBuilder.insertEmberApp (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:279:29)
    at AppBuilder.prepareAsset (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:461:18)
    at AppBuilder.prepareAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:471:18)
    at AppBuilder.updateAssets (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:538:27)
    at AppBuilder.build (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/app.js:619:38)
    at WaitForTrees.buildHook (/Users/ceppstei/Projects/contrib/embroider/packages/core/src/build-stage.js:37:31)

=================================================================================
</pre></details>

**Comment by chriseppstein** [comment] 2020-12-05 05:54
@thoov After testing this more, I still don't think it's working right. The build succeeds but the lazy engine's css isn't in the dist directory after the build is complete.

**Comment by thoov** [comment] 2020-12-11 04:32
Just updating this issue in response to @chriseppstein last comment. We chatted outside of this issue and I just wanted to leave a comment here for future travelers. The lazy engine's css will be inlined into the engine's JS chunk in non production builds and does not show up as a dedicated css file in dist (it does show up if -prod is used).

**Closed** 2020-12-19 17:28 UTC
