### ISSUE TITLE
{{div}} divide helper from ember-math-helpers breaks with 2.x with use of <div> tags

### ISSUE THREAD

**Issue by ztjohns** [embroider-build/embroider#1320] opened 2023-01-06 14:13 UTC
Hello, when using ember-math-helpers in templates after turning on Embroider 2.0.2 we get the following errors from components that use this divide helper.
```
Attempted to load a component, but there wasn't a component manager associated with the definition. The definition was: Wrapper
```
**Example**
```
{{#let (div this.a this.b) as |c|}}
  <div>{{c}}</div>
{{/let}}
```
**Temp Solution**
Fortunately we only used this in two places, so I am moving all the computation in JS instead.

**Expectation**
It to work as normal

**Comment by rwwagner90** [comment] 2023-01-25 03:30
@ztjohns can you please confirm if using `{{div this.a this.b}}` outside of `#let` gives you the same error?

**Comment by ztjohns** [comment] 2023-01-26 12:37
> @ztjohns can you please confirm if using `{{div this.a this.b}}` outside of `#let` gives you the same error?

Sure thing, let me do a few examples and I will post something.

**Comment by ztjohns** [comment] 2023-01-26 12:46
> @ztjohns can you please confirm if using `{{div this.a this.b}}` outside of `#let` gives you the same error?

The following scenarios in addition to the `let` example above all cause the wrapper error mentioned:

```
<div>{{div 10 2}}</div>
```
```
<div>hello world</div>
{{div 10 2}}
```
 It seems like simply using the `{{div}}` helper in a template that has `<div>` tags fails to parse corrrectly.

**Comment by Windvis** [comment] 2023-01-26 13:09
I think the issue is that, starting with `@embroider/core` v2, components, helpers and modifiers will be automatically added to the template scope. Since your code uses the `div` helper, Embroider will add it to the scope. This has the side effect that the `div` in `<div>` is the same reference, but since it's not a component, you'll see the mentioned error message.

When using the first-class templates syntax it would look similar to this:
```gjs
import div from 'ember-math-helpers/helpers/div';

<template>
  {{#let (div @a @b) as |c|}}
    <div>{{c}}</div>
  {{/let}}
</template>
```

This version would have the same issue, with the exception that you can simply rename the helper import so it doesn't conflict with the element name anymore.

```js
import divide from 'ember-math-helpers/helpers/div';
...
```

So I think the issue is that Embroider adds references into the template scope while they might conflict with native element names. Before strict mode templates it wasn't really possible to get into this situation since all references would be prefixed with `this.div` or `@div` and there is also the [`no-shadowed-element`](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-shadowed-elements.md) template lint rule to prevent some other cases.

**Comment by ef4** [comment] 2023-01-26 13:25
I think @Windvis is right and we need to check for collisions with native events in lexical scope.

**Comment by rwwagner90** [comment] 2023-01-26 15:12
I could also easily rename this helper in ember-math-helpers, which might be a good thing to do.

**Comment by ef4** [comment] 2023-01-26 17:11
Yeah, we should fix the bug but renaming the helper is also good, because even if embroider automatically avoids the collision, users writing in first-class template syntax would still need to remember to avoid the collision.

**Comment by Windvis** [comment] 2023-03-24 09:10
I was recently testing Embroider in one of our apps and encountered a similar case with the `await` helper from [ember-promise-helpers](https://github.com/fivetanley/ember-promise-helpers#await). In this case it triggered a build error since `await` is a reserved keyword.

I re-exported the helper under another name in our app and used the updated name to work around the issue.

**Comment by void-mAlex** [comment] 2023-03-24 09:55
this class of issues should be fixed on latest unstable npm releases, we're also working on adding tests specifically for this type of case, I'll make sure to add await to the list
thanks for the report

**Comment by ef4** [comment] 2023-03-24 16:09
Yes, the exact fix was here: https://github.com/embroider-build/embroider/blob/e7c17891eef96ab35f75e7323ea39dc69a36a8b6/packages/compat/src/resolver-transform.ts#L620-L622

(And while the comment says it avoids collision with html elements, this also necessarily avoids collision with javascript keywords like `await` too.)

**Closed** 2023-04-04 19:33 UTC
