### ISSUE TITLE
How do I enable private methods?

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#979] opened 2021-09-24 18:50 UTC
I'm surprised they aren't enabled by default? because ember-cli-babel has them :upside_down_face: 

but anywho, I have this error in C.I.: https://github.com/NullVoxPopuli/ember-array-map-resource/pull/103/checks?check_run_id=3702630696#step:5:215
```
 - originalErrorMessage: /home/runner/work/ember-array-map-resource/ember-array-map-resource/-private/resources/array-map.ts: Class private methods are not enabled.
  20 |
  21 |   // @private
> 22 |   get #records(): Element[] {
     |   ^
  23 |     return this.args.positional[0];
  24 |   }
  25 |
  - stack: SyntaxError: /home/runner/work/ember-array-map-resource/ember-array-map-resource/-private/resources/array-map.ts: Class private methods are not enabled.
  ```
  
  Classic build works just fine with private fields: https://github.com/NullVoxPopuli/ember-array-map-resource/pull/103/checks?check_run_id=3702630588

**Comment by ef4** [comment] 2021-09-26 17:44
I can't reproduce this. I tested private fields working in both an app and an addon. Maybe you have old dependencies (like a `@babel/preset-env`) in a lockfile?

**Comment by NullVoxPopuli** [comment] 2021-09-26 19:11
I re-rolled the lockfile and got the same issue: https://github.com/NullVoxPopuli/ember-array-map-resource/pull/106/checks?check_run_id=3714144862#step:5:215

I think the issue is more private _method_ more than private fields -- I'm surprised these are different implementation-wise in Babel.

But yeah, private fields already work just fine.

What's goofy is that private methods are natively supported, 
![image](https://user-images.githubusercontent.com/199018/134821028-8986fb04-6eb1-4391-8241-29f31a6bc803.png)

**Comment by NullVoxPopuli** [comment] 2021-10-02 00:55
ember-cli-babel has private methods here: https://github.com/babel/ember-cli-babel/blob/085c408b88a058bdbcaa298a5e59c9511e832073/lib/babel-options-util.js#L403
but only in the else condition. :thinking: 

I searched embroider for `@babel/plugin-proposal-private-methods` but it couldn't be found. :thinking: 
I shall add it!

**Comment by rwjblue** [comment] 2021-11-17 21:56
@courajs - I don't think we are using that dep at all actually...

**Comment by rwjblue** [comment] 2021-11-17 21:56
I believe this is the same thing I described in https://github.com/babel/ember-cli-babel/issues/419#issuecomment-971787156, since we use ember-cli-babel for compilation still we're going to have the same issue.

**Comment by ef4** [comment] 2021-12-20 21:51
I suspect this is fixed by https://github.com/babel/ember-cli-babel/pull/420

**Closed by ef4** 2021-12-20 21:51 UTC

**Comment by NullVoxPopuli** [comment] 2021-12-20 21:53
I'll double check real quick

**Comment by NullVoxPopuli** [comment] 2021-12-20 22:35
I ran in to a separate issue,
About cache missing: https://github.com/NullVoxPopuli/ember-array-map-resource/runs/4588181014?check_suite_focus=true#step:5:93
https://github.com/embroider-build/embroider/issues/1020

**Comment by NullVoxPopuli** [comment] 2021-12-20 23:12
ok, too much going on here, here is the minimal test:
https://github.com/NullVoxPopuli/ember-array-map-resource/pull/212

and it succeeded! yay!
confirm fixed.
