### ISSUE TITLE
Issue with @ember-data/debug/setup.js

### ISSUE THREAD

**Issue by thoov** [embroider-build/embroider#826] opened 2021-05-28 00:03 UTC
### Steps to reproduce:

1. `ember addon foobar --yarn` (Use ember-cli 3.26+)
2. `ember install ember-data`
3. `yarn add -D @embroider/core @embroider/compat @embroider/webpack webpack`
4. `EMBROIDER_TEST_SETUP_FORCE=true EMBROIDER_TEST_SETUP_OPTIONS=safe ember s`

### Error:

```
setup.js:20 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (setup.js:20)
    at Object.../../node_modules/@ember-data/debug/setup.js (chunk.d5c0c63cbd51f4014925.js:149)
    at __webpack_require__ (chunk.72811919dc18453a17c5.js:31)
    at eval (ember-data-data-adapter.js:5)
    at Object../initializers/ember-data-data-adapter.js (chunk.68a92cf93b54bca7a7d2.js:149)
    at __webpack_require__ (chunk.72811919dc18453a17c5.js:31)
    at Module.eval [as callback] (dummy.js:22)
    at Module.exports (vendor.js:115)
    at requireModule (vendor.js:36)
    at resolveInitializer (index.js:10)
```

cc @ef4 / @rwjblue

**Comment by ef4** [comment] 2021-06-01 18:16
(Reproduction steps are missing `yarn add -D webpack` since that is now required as a peer of @embroider/webpack, but that is not the source of the bug.)

**Comment by thoov** [comment] 2021-06-01 18:43
Updated the repo steps with that

**Comment by rwjblue** [comment] 2021-07-30 15:57
Fixed by https://github.com/embroider-build/embroider/pull/880

**Closed by rwjblue** 2021-07-30 15:57 UTC
