### ISSUE TITLE
@embroider/test-setup v2 causes assertion for HTML encoded char to fail

### ISSUE THREAD

**Issue by jelhan** [embroider-build/embroider#1380] opened 2023-03-27 20:42 UTC
I noticed a regression if an application renders a HTML encoded character and asserts against the character not being encoded in `@embroider/test-setup` v2.

I have a component, which renders `&times;`: https://github.com/ember-bootstrap/ember-bootstrap/blob/d6cf431bf2871debf04915967271419a0c848fdb/addon/components/bs-modal/header/close.hbs#L2

I have a test, which asserts `assert.dom(this.element).hasText('×');`.

The assertion is working fine in non-Embroider builds and with `@embroider/test-setup` v1. But it starts to fail when upgrading to `@embroider/test-setup` v2: https://github.com/ember-bootstrap/ember-bootstrap/pull/1857

Asserting against the encoded HTML character works with `@embroider/test-setup` v2 but does not work with non-Embroider builds. At this point I'm stuck.

**Comment by jelhan** [comment] 2023-03-28 12:35
> I vaguely remember you had brought up a similar issue before, right? What was the problem then, and the fix?

I mentioned that issue some weeks ago on Discord. But haven't had time to create a GitHub issue yet. Noticed it first in Ember Bootstrap around January. Not solved yet. Just haven't had time to get back to it.

**Comment by jrjohnson** [comment] 2023-05-19 05:48
I'm seeing this issue with embroider v3 in our [embroider tests](https://github.com/ilios/common/actions/runs/5018590325/jobs/8998311400?pr=3364#step:5:701) as well. I'm unable to reproduce it in a simple app, it may have to do with the number of `{{outlets}}` or something else about nesting because it doesn't happen for things in `application.hbs`, but starts to happen at some point in the tree. I'm going to keep playing with a test app to see if I can find the failure point, but something is weird here for sure.

**Comment by ef4** [comment] 2023-05-19 11:53
This looks like a glimmer printer bug. In a quick check, it looks like parsing and re-printing a template does:

```diff
-&times;
+&amp;times;
```

If I'm right, this bug happens only in components inside addons, and only when those addons have some custom AST transforms applied. Under those conditions, embroider needs to compile away the custom stuff before the app builds, so it will run the component's template through the template compiler, re-serializing to hbs after transforming.

**Comment by ef4** [comment] 2023-05-19 11:54
Might be fixed already and we're not using the right setting here: https://github.com/glimmerjs/glimmer-vm/pull/938

**Comment by ef4** [comment] 2023-05-19 13:17
Fixed in babel-plugin-ember-template-compilation 2.0.3. As it's a patch release, no embroider release is needed, just make sure you let your deps float (or patch your lockfile) so you get the update.

**Closed by ef4** 2023-05-19 13:17 UTC

**Comment by jrjohnson** [comment] 2023-05-19 15:53
Thanks @ef4, this fixed the issue for me 🎉
