### ISSUE TITLE
All ember-source modules missing from a build

### ISSUE THREAD

**Issue by vlascik** [embroider-build/embroider#1116] opened 2022-02-08 04:37 UTC
Seems that all modules from ember-source end up missing from `/assets/my-app.js` and the build fails with errors like these:

```
ERROR in ./components/-dynamic-element-alt.js 1:0-41
Module not found: Error: Can't resolve '@ember/component' in '$TMPDIR\embroider\889da1\components'
 @ ./assets/my-app.js 383:13-62
 
ERROR in ./components/badge.js 1:0-67
Module not found: Error: Can't resolve '@ember/component/template-only' in '$TMPDIR\embroider\889da1\components'
 @ ./assets/my-app.js 395:13-47
```

I understand that's a pretty vague error description, so maybe someone familiar with the source code could provide some pointers as to what to check, e.g. where this list of modules in my-app.js gets created, so that I can start debugging from there.

Thanks.

compat build, require('@embroider/compat').compatBuild(app, Webpack);
ember-source:  4.3.0-alpha.3
ember-cli: 4.2.0-beta.1
node: 14.16.1
os: win32 x64

**Comment by mehulkar** [comment] 2022-02-11 00:58
May be related, I also see this:

```
Module not found: Error: Can't resolve '@ember/string' in '$TMPDIR/embroider/84850c/components/blahblah.js'
```

In my case since `@ember/string` is a real package published to npm, I was able to fix by installing it for real.

**Comment by ef4** [comment] 2022-02-11 01:14
Neither of these should happen, all of thee imports are supposed to get rewritten to point at things coming from ember-source before webpack sees them. Can somebody share a reproduction that does this?

**Comment by mehulkar** [comment] 2022-02-11 01:58
Just tried in a brand new app (3.28) and was unable to repro (embroider v1.2.0). Must be something else in my main app. Sadly decided not to hold onto that play branch so I'll have to repro and look at debug logs again later!

**Comment by NullVoxPopuli** [comment] 2022-02-13 00:54
I have a reproduction -- kinda happened by accident -- but ran in to this error:
```
Module not found: Error: Can't resolve '@ember/component' in '<repo>/ember-popperjs/dist/index.js'}
```

https://github.com/NullVoxPopuli/ember-popperjs/pull/142

test-app has ember-source 4.1.0

**Comment by NullVoxPopuli** [comment] 2022-02-15 03:00
Another repro: https://github.com/NullVoxPopuli/ember-functions-as-helper-polyfill/pull/111

:thinking: Surely there is something common between all these :thinking:

**Comment by ef4** [comment] 2022-02-15 22:31
There are probably at least two different bugs being reported in this thread now. It matters whether the place that is failing to import from ember is code in the app or code in an addon (and whether that addon is a v2 addon).

I looked at the ember-functions-as-helper-polyfill reproduction and that is a failure coming from inside ember-welcome-page (a v2 addon in the test-app). 

It's probably a different bug from the original report.

**Comment by MichalBryxi** [comment] 2022-02-20 17:56
I had success by [removing ember-welcome-page](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations/-/merge_requests/119/diffs?commit_id=a02f22cd36d683a838382b3f25923ac1c251266c) when migrating to v2 addon format `[ember-intl-changeset-validations](https://gitlab.com/michal-bryxi/open-source/ember-intl-changeset-validations). Feel free to grab the branch & investigate.

**Comment by mehulkar** [comment] 2022-03-07 21:22
I've gotten my app back into this state and have saved the branch this time (now with `@embroider/*@1.4.0`. It reproduces consistently, and I see errors on every reference of `@ember/string`.

```
Build Error (PackagerRunner) in components/we-modal.js
Module not found: Error: Can't resolve '@ember/string' in '$TMPDIR/embroider/84850c/components/we-modal.js'
```

> It matters whether the place that is failing to import from ember is code in the app or code in an addon

In my case, the import is in a component in my app (not from an addon). I tried running with `DEBUG=ember-cli:*,embroider:*` , but seems the error is in webpack land.

**Comment by ef4** [comment] 2022-03-08 02:09
Does it keep reproducing after you `rm -rf $TMPDIR/embroider/webpack-babel-loader`?

**Comment by ef4** [comment] 2022-03-08 02:22
Also, do you have `@ember/string` and which packages are consuming it? `yarn why @ember/string`

**Comment by mehulkar** [comment] 2022-03-08 07:10
> Does it keep reproducing after you `rm -rf $TMPDIR/embroider/webpack-babel-loader`?

Yeah.

**Side note**: Does `$TMPDIR` remain the same between clean builds? 

I used the one where the full stack trace from the build (before `rm -rf`), and it turned out that it was the same again in the second build where I repro'd, but I'm not sure if that's a coincidence or what.)

(`Stack Trace and Error Report: /var/folders/dw/l307h_b16vzc0wys2f_nbmm00000gn/T/error.dump.2ac43f103a9bc69ff15ce572ccd476ed.log`, 


> Also, do you have `@ember/string` and which packages are consuming it? 

<details>
<summary>Output of `npm ls @ember/string` shows ember-data as the only consumer</summary>

```
─┬ ember-data@3.28.8
  ├─┬ @ember-data/adapter@3.28.8
  │ └── @ember/string@3.0.0  deduped
  ├─┬ @ember-data/debug@3.28.8
  │ └── @ember/string@3.0.0  deduped
  ├─┬ @ember-data/model@3.28.8
  │ └── @ember/string@3.0.0  deduped
  ├─┬ @ember-data/store@3.28.8
  │ └── @ember/string@3.0.0  deduped
  └── @ember/string@3.0.0 
```

</details>

I tried `npm uninstall --save ember-data` (and confirmed that `npm ls @ember/string` is empty, and it still reproduces, so I think `ember-data` is a red herring here. (Another tip off to that is that I actually have `addons.blacklist = ['ember-data']` configured for my build, but for Reasons™️, it's still it's in my dependencies.)

**Comment by NullVoxPopuli** [comment] 2022-05-08 13:20
I'm gonna log how I'm trying to debug this in this comment. (I'll be updating the comment instead of adding more posts as I figure things out).

------------------------

The original error I got ended with
```
16 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
```
But adding that to the webpack config (in my autoImport config at the time of debugging) had no effect, so I assume the `stats` option isn't being merged.
Instead, I `cat`d the full error log and placed a breakpoint _in_ webpack here:
![image](https://user-images.githubusercontent.com/199018/167298120-a6246475-3af7-4e83-bf3d-8d2b63ce6309.png)

**Comment by NullVoxPopuli** [comment] 2022-05-27 23:06
Got another occurrence here: https://github.com/CrowdStrike/ember-aria/pull/6

Though, not sure what the difference is between that an ember-resources.
Both are v2 addons, yet ember-resources' test app boots.
More diffing required ahead!

**Comment by NullVoxPopuli** [comment] 2022-05-28 01:01
alright, so my issue was that the v2 addon didn't have `"keywords": [ "ember-addon" ]`

(at least most immediately, I have other things to figure out as well)

**Comment by NullVoxPopuli** [comment] 2022-07-20 14:07
@vlascik do you still have this issue / did `keywoards: ['ember-addon']` in the package.json resolve it?

**Comment by vlascik** [comment] 2022-07-22 05:47
@NullVoxPopuli well, my original problem (all ember-source modules missing) seems to be resolved - the app builds and boots.

However, some modules are still missing - as far as I can tell the scenario is this:
1. app depends on an ember addon
2. addon depends on a generic JS library, not an addon

I was able to create a reproduction here https://github.com/vlascik/repro-embroider-missing-modules

Vanilla ember new app depends on `ember-changeset`, which in turn depends on `validated-changeset`. App builds, but fails to boot with:
```
Uncaught Error: Could not find module `validated-changeset` imported from `(require)`
    at missingModule (node_modules\@embroider\synthesized-vendor\vendor\loader\loader.js:247:1)
    at findModule (node_modules\@embroider\synthesized-vendor\vendor\loader\loader.js:258:1)
    at requireModule (node_modules\@embroider\synthesized-vendor\vendor\loader\loader.js:24:1)
    at eval (validated-changeset.js:1:18)
    at ../externals/validated-changeset.js (chunk.2c1f9ffb38eea73b66f3.js:721:1)
    at __webpack_require__ (chunk.6c61298b501950d139e4.js:31:41)
    at eval (application.js:5:88)
    at ./routes/application.js (chunk.2c1f9ffb38eea73b66f3.js:260:1)
    at __webpack_require__ (chunk.6c61298b501950d139e4.js:31:41)
    at Module.eval [as callback] (repro-embroider-missing-modules.js:103:147)
```

because of an import from `validated-changeset` at `routes/application.js`.

**Comment by NullVoxPopuli** [comment] 2022-07-23 14:45
> Adding validated-changeset to app's devDependencies "fixes" the problem.

This is the correct behavior, in modern packagers, you cannot import from things you do not, yourself, declare

**Comment by NullVoxPopuli** [comment] 2022-07-23 14:46
Gonna close this for now -- if anyone is having a similar error, let's open a new issue so we don't get distracted / confused (I would!) with all the things in this thread.

**Closed by NullVoxPopuli** 2022-07-23 14:46 UTC

**Comment by vlascik** [comment] 2022-07-23 15:06
@NullVoxPopuli Got any link for that? Because as far as I was able to find, webpack shouldn't care where was dependency declared, as long as it is in node_modules, and builds its own dependency graph based on import statements https://webcache.googleusercontent.com/search?q=cache:xN1si4ZIZLwJ:https://blog.jakoblind.no/how-webpack-decides-what-to-bundle/

Also, the behavior of classic ember build system, where addon's `dependencies` went into the host app, is well known and relied upon, so if embroider changes that, users should be either be notified in build/boot output, or the change needs to be well documented, otherwise you'll create a lot of confusion.

**Comment by NullVoxPopuli** [comment] 2022-07-23 15:51
> as it is in node_modules

this is the kicker, you can't guarantee it is, because how node_modules is organized is an implementation detail of the package manager. in both yarn@v1 and npm (which have broken dependency management techniques, though npm@8 is quite a bit better), the will shove everything flatly into node_modules -- this gives you the illusion that you can import your transient dependencies. What yarn3, pnpm, and npm@8 (with strict settings still enabled) do is manage deps correctly, in that you can only import what is declared in your package.json.

This isn't an emborider issue -- embroider is following the correct resolution algorithm, in that it doesn't re-implement bugs that yarn@v1 and older npm contain
