### ISSUE TITLE
ReferenceError: emberAutoImportDynamic is not defined -- using emberfire

### ISSUE THREAD

**Issue by knownasilya** [embroider-build/embroider#389] opened 2020-02-17 17:15 UTC
```
Uncaught (in promise) ReferenceError: emberAutoImportDynamic is not defined
    at FirebaseAppService.auth (firebase-app.js:18)
    at ApplicationController.login (controller.js:37)
```

which is from https://github.com/firebase/emberfire/blob/v3.0.0-rc.6/addon/services/firebase-app.ts#L28

The app uses    `"ember-auto-import": "^1.5.3",` and `"emberfire": "^3.0.0-rc.6",`

**Comment by ef4** [comment] 2020-02-17 17:46
It looks like when embroider disables ember-auto-import (because embroider has that capability natively) it's failing to also disable ember-auto-import's babel plugin that rewrites dynamic import.

A workaround you can try just to get past this and confirm the problem is to comment out this: https://github.com/firebase/emberfire/blob/3f23274ed72a2d890894cbd87fdcae2f42ee4905/ember-cli-build.js#L9

**Comment by ef4** [comment] 2020-02-17 20:34
Fixed by #390

**Closed by ef4** 2020-02-17 20:34 UTC

**Comment by knownasilya** [comment] 2020-02-17 21:01
The workaround did fix

**Comment by kturney** [comment] 2020-05-06 22:52
We are seeing this with embroider 0.15.0 trying to use https://github.com/kturney/ember-mapbox-gl 1.0.0.

Should ember-mapbox-gl be checking something to conditionally add the babel plugin?

**Comment by bobisjan** [comment] 2020-10-25 12:43
I see same error directly from app

- `ember-auto-import@1.6.0`
- `@embroider/compat@0.28.0`
- `ember-cli-babel@7.23.0`

```js
// ember-cli-build.js
babel: {
  plugins: [require('ember-auto-import/babel-plugin')],
},
```

```
error-handler.js:26 emberAutoImportDynamic is not defined
ReferenceError: emberAutoImportDynamic is not defined
    at ModuleLazyLoaderService.load (webpack:///./services/module-lazy-loader.js?:78:9)
    at TelephonyService.loadPhoneNumberLibrary (webpack:///./services/telephony.js?:786:34)
```

**Comment by zion03** [comment] 2020-12-25 22:32
Embroider: 0.35.0

The same error:
`import('cropperjs').then((module) => {`
from
https://github.com/danielthall/ember-cropperjs/blob/master/addon/components/image-cropper.js#L77
throw 
`Uncaught ReferenceError: emberAutoImportDynamic is not defined`
And looks like:
` emberAutoImportDynamic('cropperjs').then(module => {`
